name: Bug Report

description: Report a reproducible bug in Sidra.

title: "[BUG]: "

labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting this issue.

        Please fill all required fields before submitting.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the issue.
      placeholder: Example - Homepage crashes after login.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Explain exactly how to reproduce.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
        - Brave
        - Other
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device
      options:
        - Desktop
        - Android
        - iPhone
        - Tablet
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      placeholder: v1.0.0

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have verified this issue is reproducible.
          required: true
